apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:npzpkzQQy+dKf30z7nC5DDGh5rpW1CBsZ8JVWbt1+Z9vny/sLeovMl+MI1P/Oea3E5YQRfZkH7a3Ieq5kzt6xqQw9eusYbieqrkhlgHoxz27VPYWiqBrvsee0Z9Kwe8eDRCGXyI4fOSZj4Sphi1AsIdqKcbKFsxvARwBQTiQ4DZQilSChnOz5dkP0IPOfo3YpYFY4K9aw0B4DqNf8WSlS6SsLc2oE+KyEICgCaBLFq9oAsUcCEItrZFTtsWrtiGQl/BmzI60fwzgcu7Skt/6E2hXHckN6D9RkvsfqgXsmaGdeq5ef/Q26bmrftXz2tcDGCnsZndw3MsUvPKMKiVGu4E+lLUGhxr+/0DJETAyrm208wUmOavRZ35rgfgRKjvO,iv:yTr2oqDW/SKcXkfMWXrnuJivuIV3zNk8Y2Q85vAGDww=,tag:dC5vix4vfgN7dSYmd5IyCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:hzwf0VhiDOvsNaM+R16Q0g+BrHPWgbSXIi42S/X+GBQ3D8p2moJW2ZrjtXi1UzLiN1KUjhSxfEtgFTY+yKHsmOsLAuDXP+JOXB21GPsO2M5/YLlp+cGqdDtIZ756j8nKcApvcKi+PN5NajJbUvEQuTCB4kH8xUzvNQAgeEpHeiYBuTAKwOo8KGy7O/m0+29fBV9GMcn7z5lRBdQLlhhT7Ce7NKvuDI2P+Rnqj+3q/s+rgr+7ez7PVBM9lkA0lgAweFXjygVuAG3Kxa+n3Q==,iv:nk64Nse9Auwr84AZQDcfJSWu/ps0/PGUb1ZSQp9JZ9Q=,tag:71UnETlUezbJOE4yEvTLig==,type:str]
    known_hosts: ENC[AES256_GCM,data:kUEgG4UFDViU9X+dBsMX/yMLVTtx3lxuO49Amb3kS6s6GfDkbGKw+3G7h17wLx00nPJ99KPsmR4S4k8aLRD3Pa9kGvXu/2x9wkKK4ryGL1zLPfX/4v89ycGqmnRpqgqTQgpXotrhWGNWONUwj+J/7MukAo099O9He06F0RCgO04jYrEoXwh0jeHcWee3l+VA2+J3WLe30Ok/DLMQtvDBmCMdFWUPBqXZGEbB,iv:3h5TKCDOkZBHgDfS4tK3FDt8TUGnu/xgleNO3GAkMPc=,tag:8Q8bib+icCWUkGoUWiPZHQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bFg0elVBYlRnN3ZrbllQ
            QktMWTJVVllsR0RiYXBJRVBjTlNVZWhuTVRvClBKOUN3OGJQL2xCQi9PclJCY2hO
            WEFaR2ZvU3hONExrc2d3aE9ZL2E5V1UKLS0tIHRyUGM4cXUvMEFEK3RYK3Y1anpB
            Y0toVXZhYW9XaGZDS3hpcWI1T004RXMK8lLH/9hGNxg3dKsfcJkzLiAuiktxp4ZL
            Zttdsx7pXk668Dtpr5wBSCAkeZhlr2JmLKwtJhpRz8SNROVPvTkGzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:45:00Z"
    mac: ENC[AES256_GCM,data:mhnT1XWri61BdXsG25XGK7WMtDjNynXl5k2QSL/WGTlln21GEYenR7Ad2V9w0U3DAtKaYrzNsIQFmBZPMfgAQtt/BoFVyq0rUZZGXO8sKE9T1cSHooS/FpUgLbZLsPuT8MNsIbIYRCWgPXNfeCgKwZihqblZ7TGF0eKw79clOMg=,iv:g4LMHLtsTUBE/y7ntdSU6VDro6WJtVQIwGsIgXJwhWU=,tag:a7erBonxXU1dqJuqXDYtGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
