apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VJmlBZ1FGFx4PjYwSNgiuS3impaVlzBLRjpAGPuRboUR1nIhF6DJmR5SVquT50xjJFNr+lH952lu5KtL2MiIzRrrcrJJ4U5AoHxO03xqLIKaGuC128gSR8IKLE/6ZNjqGJeX56vmRaB+kQBEmmBbgVQIbhWpmuagW3vcdk1tFkx+w8WUSmxlt+lPxlmFTK+E3OPJKlYYRuJ5Ohwfz+ymoHdnKWEIDsrKg46AJs16PokOIwcIVU4B5QFrgoxB7z5KoeAqeoD562xkDpmT2jcyW8bMLq1CB02D9tCa/ORNhRdR0Clu8DVgLUtWtQo1YfLy+ghtZ1cQxfIzaFoWP4Sjo0VNPn8Z445ktLfivrk976h8dAhzVMCAjpP8/8J75BWJ,iv:aBp45bMpLfNW0Z1R/f0AJNLhyjkSz593vIJR9/kcjdA=,tag:ez+oXdTh4ChFuGEXZTgMxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:J+uGulfsyzH9llydLI2cj8+jtYrRACgBe/MFnRQRDQyl+Id8kzVosTeNdO32wGL3ceqSLz3yo6bzBpcqp1FeQsmRypmoqmrgk1nPvwNFi9todGY5R7rb7kGrjhW6PuLlWmEptyW293HUJvcXFLhqnDpqJ9bwMhU4F4Xt4xBv2wGNqLxtNkNTC0WMbaI/6eW40Injg4qCABZoELzFBion42rHxcab6G0oGczMm096ZRzeliVOAfmetd3xT+KchnMS7BDVNzWILduEZdJHuQ==,iv:Bqg/AD4aJMl5NLmWmXHFP7NqMrhOOt0Zb8wft8n5uAI=,tag:cN3kU6yXiOjHDfaI5T2PAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/JOItZ6T/ZWDPJwvfF+9VWAVHZC5uTTXPyS7kW9/78UlMRBPJHSDRPdKxEXJDfYGPy4tkarUBtpkxmMZkWQNzmrrCLCltcUrnfcmU5PWP0PhT8qZsN4m1Q1VDHj5XIPctsOzVDZRNWwaorpfJuSG3+rvnz1mK+x1tp2Dlr9h1coJ540KrO0VKarFDQLcWOVrKac/ZsI+yhb71hMZbm+AYD5A+S64n30YiJeP,iv:jqZQSftiCWpBtro97+iY6gbulan7u9w3/5azQ8DDm2g=,tag:8j3gwKoE39fu3ohKkS80mw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRWZXeEdobGNVQ0tvdUgr
            NlZWYktjR1lCSi9RRmNzN0h4NzhWMVN6dVdzClRneitUWTJyeWgwVG9wTlBJKzJD
            RmpPVW1lN2Z3SnpDbmRteXpOSlU0eDgKLS0tIE1ydXlrUGlDQ2pkRjZ2dllsZ1Bp
            Y2twUElBTWZ4aHkrQVNZV090SlVHSEEK/EZ1qz7s6t2uQsx4BBDplINpGb9M6oz6
            9DVo89VIpukkYPqwUNdFk32kNgm6MUQvmxJM9i56qCz02cRVQSxPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T17:24:04Z"
    mac: ENC[AES256_GCM,data:jtOHxE3fCWZtdQIlwbUIJ2lDYVE7i2apXrywivSfewHgfXtVIi875X+9mc7Y/o4scWuQ0KH/UKkk4nzH7q4Kk8YuuW+jQ5G/hnx4AibYWkdcAiv4dcRLiZKKc7FhMzMTvHbbbs7vUTnfiohJWHwD2bvzLuH6NUkXUN+HaG8U6jw=,iv:hK6D9yuGVV8hnVhyrH6LQ2suAw8FYbYylMLn+aH6qLk=,tag:g0+7C7vQ+6d5bGxIZ7TaCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
