apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DG0xcA7XCZHZS+oPYPM6XceD0qlf8GpdNZe/8/7+WoEljssw0uR2uDBg+SLs385ZjexNbx4g/bNza1t41b5eVzy+qXWI6yBdPcvOM0jnZqfVRfp0UNdrmNvYNGRQ5Jy79O2XJzkTaSZopx2fapIrViXTKMVnt7bHh/qfbFk63Bx/Jjkvdg0nxZJU1QHzvJr+q2pFrEAs9v+EIuHG7okvCwkjVXTmDgRcL2vs6lcSXZTGQXq82h7QyGsBHdJggliuYdmGWQeoL52IYeOIkWTVFw9Oe/quZpxLkeLzqqRg/JHf/TlKj8LIwU8Rw9GgvlrQ2tIkyg/E/k2psKzazC9zWmkhJBjlMNE/KQ2KHZhCT1xPSEHJdN1Os+OmPUYlvavS,iv:l0yohTiIVNBaRLja0B7D7J1EEEzC/NohCo/9tC38BRU=,tag:kLI4v9xh9j4if9Z92/54og==,type:str]
    identity.pub: ENC[AES256_GCM,data:ACo4UPeXwCdgaRS0L+pG8VLoHf4QpTrBMap89xJSj0bWIHdwTvVqraD/cMYdHWDR7YCvWTWn9apF79XaygmzG20HkrUwsRL6X4R9UVgfba/aD/hYVa9LWYQYmeuoTnCW8ArZbfCS2hXImywkS3QJKmTaZiZFnkh8pTm2KEPrurfqRp2Eu9ZrBRmAG4jatRKlEVhGbnXhdeNCrAtkIUGbk53FQ11s1+3lBrWI0e+ao32hIJF89Yc1L1YIwtOJzkXVh3Vso54ix3J1pb1FRg==,iv:HAheIDbgcrKUUwHou6cSVsZN599EK/XigbzQCaRU5Zs=,tag:NZsABWZzs/aMgEfFAhasrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:OBtQjQ0VsU8WNYF7weLUE19/EB1NRCVJsLId2o8eFTlb0/0yarbya0qBCCHG7qdUjoIZhyn9ZorOa6KheudvSIjTqeVaj03FNytf0h9s0ObijKcRQJGXvlRlmx2MUIsyLgj9LSKYr8UwycSe5hOQ+nN8Z77iRUjwof9Ow+RjQxzmZdKDKkD4rA0HyodX6caNb2N22TNNIAMRI9iXhpPS3gv7cG6lW//PxQ6J,iv:N9Zp8RoU2aMy30P/DnZhjnqyZD70KC1X27loNGK8cgs=,tag:lrEKFxz3V61HMqFyYkFvEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbmNzQytmSHZDZnhwcEp3
            bjkyUlh5Y3g4WldtL05WakpORXZhdnY5eEJNCnRIWG1FWUg0dGZwcG4xOXVLVEUv
            T1dDM3JtdWJ0Wi9pS0lSYy9XQUpwQUkKLS0tIGZFU0JqVnYwOFQrZ0ZRMWgvLy8r
            RjlxQnFGc280eVZCWGdGenlaVTdjS1UKzUOlN3z9ajrCSm0QbdLjRuySrBfcO2QA
            ofFArMLE1vO1R0Vy7cnugXHvfWzNkvVIHByj0i88VdhSIYMyC3YQ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:14:39Z"
    mac: ENC[AES256_GCM,data:X57uvx91pbNIEYDCIhxqQ0yiK3VxciQc7iksw9/QSmPuUBe6/r1tvKoqf1f9jVa5js2qN3+u3M1dVbuOEBGv7Hby6OCgq40zsZs2HM53OHU55pLQDuPeM01ngUirgb9QV34TopMynPkCJhaLhQseQdTB5WAfZAz6QWUWCCmKt0o=,iv:xO6xvtqSjuhiG0XUoQFN4L5HpCsHsbrZhSyDZHkbgYA=,tag:BYmIYhecjDJQr5btzA0jiQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
